name: praxis_flutter
description: Praxis For Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">2.12.0 <=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  go_router: ^8.0.3
  flex_color_scheme: ^7.3.1
  cupertino_icons: ^1.0.5
  get_it: ^7.2.0
  injectable: ^1.5.3
  connectivity_plus: ^2.3.9
  url_launcher: ^6.1.6
  shared_preferences: ^2.0.15
  equatable: ^2.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  firebase_analytics: ^10.4.4
  firebase_app_check: ^0.1.5+1
  firebase_messaging: ^14.6.5
  firebase_dynamic_links: ^5.3.4
  firebase_in_app_messaging: ^0.7.3+4
  firebase_app_installations: ^0.2.3+4
  google_sign_in: ^5.4.2
  flutter_local_notifications: ^12.0.1+1
  permission_handler: ^10.1.0
  shimmer: ^2.0.0
  uuid: ^3.0.6
  intl: any
  google_fonts: ^4.0.3
  rxdart: ^0.26.0
  just_audio: ^0.9.33
  audio_service: ^0.18.9
  bloc_concurrency: ^0.2.2
  freezed_annotation: ^2.4.1

  clean_architecture:
    path: ./clean_architecture
  praxis_flutter_domain:
    path: ./praxis_flutter_domain
  praxis_data:
    path: ./praxis_data


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.1
  injectable_generator: any
  build_runner: any
  flutter_gen_runner: any
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  sqflite_common_ffi: ^2.2.1+1
  freezed: ^2.4.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - images/
