name: praxis_flutter_domain
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">2.15.1 <=3.3.0"

dependencies:
  equatable: ^2.0.5
  clean_architecture:
    path: ../clean_architecture

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.1
  build_runner: any
  mocktail: ^0.3.0
